version: '3.9'

services:
  server:
    build: .
    image: server_image
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/newsData_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=newsData_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password