DROP TABLE IF EXISTS newsData CASCADE;

CREATE TABLE IF NOT EXISTS newsData
(
    newData_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_name     VARCHAR(255)                          NOT NULL,
    subjectMatter   VARCHAR(512)                          NOT NULL,
    news            VARCHAR(512)                          NOT NULL,
    CONSTRAINT pk_newData PRIMARY KEY (newData_id)
    );